<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Posicion</th>
      <th>KM actutal</th>
      <th>Marca</th>
      <th>Placa</th>
      <th>Modelo</th>
      <th>medida</th>
      <th>R1</th>
      <th>R2</th>
      <th>R3</th>
      <th>Estado</th>
      <th>Registrado</th>
      <th>Observaciones</th>
      <th>Presion de aire</th>
      <th>Accion</th>
    </tr>
  </thead>
  <tbody>
    @foreach ($tire as $truck)
    <tr>
      <td>{{$truck->id}}</td>
      <td>{{$truck->posicion}}</td>
      <td>{{$truck->KM_actutal}}</td>
      <td>{{$truck->brandTire->nombre}}</td>
      <td>{{$truck->truck->placa}}</td>
      <td>{{$truck->modelo}}</td>
      <td>{{$truck->medida}}</td>
      <td>{{$truck->R1}}</td>
      <td>{{$truck->R2}}</td>
      <td>{{$truck->R3}}</td>
      <td>{{$truck->estado}}</td>
      <td>{{$truck->user_name_insert}}</td>
      <td>{{$truck->observaciones}}</td>
      <td>{{$truck->presion_aire}}</td>
      <td>{{$truck->accion}}</td>
    </tr>
    @endforeach
  </tbody>
</table>