<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Dni</th>
      <th>Password</th>
      <th>Role</th>
    </tr>
  </thead>
  <tbody>
    @foreach ($users as $user)
    <tr>
      <td>{{$user->id}}</td>
      <td>{{$user->name}}</td>
      <td>{{$user->dni}}</td>
      <td>{{$user->password}}</td>
      <td>{{$user->role}}</td>
    </tr>
    @endforeach
  </tbody>
</table>